### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#6]
C:\gbf-weap-master>python weapon-optimizer.py fire-weapons.json fire-summons.json
Traceback (most recent call last):
  File "weapon-optimizer.py", line 5, in <module>
    from wep_types import WeaponSkill, WeaponType, SummonType, Weapon, Summon
  File "C:\Users\srwgi\Desktop\1\gbf-weap-master\wep_types.py", line 1, in <module>
    from enum import IntEnum
ImportError: No module named enum

**Comment by srwgin** [comment]
solve forget install enum34
pip install enum34-1.1.3-py2.py3-none-any.whl
